<?php

namespace Database\Seeders;

use App\Models\Problem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GanreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        // ======================= history ============================
        Problem::create([
          'pstyle'=>'1',
          'answer_text'=>'鎌倉時代において、日本を支配したのはどの武家政権でしょうか?',
          'pre_answer'=>'平安朝＃藤原氏#鎌倉幕府#後醍醐天皇',
          'correct_answer'=>'鎌倉幕府',
          'ganre_num'=>'1',
          'province_name'=>'22',
          'level_num'=>'1',
        ]);
        Problem::create([
          'pstyle'=>'1',
          'answer_text'=>'平安時代において、現在の京都市にあたる地域に都が置かれました。この都の名称は何でしょうか?',
          'pre_answer'=>'平安京＃鎌倉#江戸#奈良',
          'correct_answer'=>'平安京',
          'ganre_num'=>'1',
          'province_name'=>'2',
          'level_num'=>'1',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'室町時代において、南北朝時代の混乱を終息させ、日本を統一した室町幕府の初代将軍は誰でしょうか?',
            'pre_answer'=>'足利義満＃足利義政#足利義詮#足利尊氏',
            'correct_answer'=>'足利尊氏',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'江戸時代において、幕府が導入した身分制度のうち、最下層に位置したのはどの身分でしょうか?',
            'pre_answer'=>'武士＃農民#商人#えた・庶民',
            'correct_answer'=>'えた・庶民',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'明治維新により、日本における徳川幕府が倒され、明治政府が成立しました。明治維新を主導した人物は誰でしょうか?',
            'pre_answer'=>'徳川慶喜＃西郷隆盛#伊藤博文#大久保利通',
            'correct_answer'=>'西郷隆盛',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
          'pstyle'=>'2',
          'answer_text'=>'鎌倉時代において、日本を支配したのはどの武家政権でしょうか?',
          'pre_answer'=>'平安朝＃藤原氏#鎌倉幕府#後醍醐天皇',
          'correct_answer'=>'鎌倉幕府',
          'ganre_num'=>'1',
          'province_name'=>'2',
          'level_num'=>'1',
        ]);
        Problem::create([
          'pstyle'=>'2',
          'answer_text'=>'平安時代において、現在の京都市にあたる地域に都が置かれました。この都の名称は何でしょうか?',
          'pre_answer'=>'平安京＃鎌倉#江戸#奈良',
          'correct_answer'=>'平安京',
          'ganre_num'=>'1',
          'province_name'=>'2',
          'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'2',
            'answer_text'=>'室町時代において、南北朝時代の混乱を終息させ、日本を統一した室町幕府の初代将軍は誰でしょうか?',
            'pre_answer'=>'足利義満＃足利義政#足利義詮#足利尊氏',
            'correct_answer'=>'足利尊氏',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'1',
        ]);
        Problem::create([
            'pstyle'=>'2',
            'answer_text'=>'江戸時代において、幕府が導入した身分制度のうち、最下層に位置したのはどの身分でしょうか?',
            'pre_answer'=>'武士＃農民#商人#えた・庶民',
            'correct_answer'=>'えた・庶民',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'2',
            'answer_text'=>'明治維新により、日本における徳川幕府が倒され、明治政府が成立しました。明治維新を主導した人物は誰でしょうか?',
            'pre_answer'=>'徳川慶喜＃西郷隆盛#伊藤博文#大久保利通',
            'correct_answer'=>'西郷隆盛',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'answer_text'=>'次のうち、第二次世界大戦後の日本の主要な政党はどれか。（複数選択可）',
            'pre_answer'=>'自由民主党＃日本共産党#社会民主党#公明党',
            'correct_answer'=>'自由民主党#社会民主党#公明党',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'1',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'answer_text'=>'次のうち、江戸時代に起こった事件はどれか。（複数選択可）',
            'pre_answer'=>'島原の乱＃大塩平八郎の乱#明治維新#花咲徳栄一揆',
            'correct_answer'=>'島原の乱＃大塩平八郎の乱#花咲徳栄一揆',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'answer_text'=>'次のうち、日本の戦国時代に活躍した武将はどれか。（複数選択可）',
            'pre_answer'=>'織田信長＃徳川家康#上杉謙信#武田信玄',
            'correct_answer'=>'田信長＃上杉謙信#武田信玄',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'answer_text'=>'次のうち、日本の宗教はどれか。（複数選択可）',
            'pre_answer'=>'神道＃仏教#キリスト教#ユダヤ教',
            'correct_answer'=>'神道＃仏教#キリスト教',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'3',
            'answer_text'=>'昭和時代において、日本は太平洋戦争に参戦しました。この戦争において、日本が降伏したのは何年でしょうか? （複数選択可）',
            'pre_answer'=>'1943年＃1944年#1945年#1946年',
            'correct_answer'=>'1945年#1945年',
            'ganre_num'=>'1',
            'province_name'=>'2',
            'level_num'=>'1',
          ]);
          // =============food====================
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な魚料理はどれか。',
            'pre_answer'=>'すき焼き＃おでん#天ぷら#寿司',
            'correct_answer'=>'寿司',
            'ganre_num'=>'2',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'
            次のうち、日本の代表的な麺料理はどれか。',
            'pre_answer'=>'うどん＃そば#ラーメン#パスタ',
            'correct_answer'=>'ラーメン',
            'ganre_num'=>'2',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な和菓子はどれか。',
            'pre_answer'=>'クレームブリュレ＃チーズケーキ#大福#シュークリーム',
            'correct_answer'=>'大福',
            'ganre_num'=>'2',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な野菜料理はどれか。',
            'pre_answer'=>'カレーライス＃オムライス#お好み焼き#きんぴらごぼう',
            'correct_answer'=>'きんぴらごぼう',
            'ganre_num'=>'2',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な飲み物はどれか。',
            'pre_answer'=>'コーヒー＃ジュース#日本茶#紅茶',
            'correct_answer'=>'日本茶',
            'ganre_num'=>'2',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        
        // ==============   travel   ====================
        
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'
            次のうち、日本の代表的な観光地はどれか。',
            'pre_answer'=>'グランドキャニオン＃エッフェル塔#富士山#ニューヨークのタイムズスクエア',
            'correct_answer'=>'富士山',
            'ganre_num'=>'3',
            'province_name'=>'2',
            'level_num'=>'1',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'
            次のうち、日本の代表的な祭りはどれか。',
            'pre_answer'=>'マルディグラ＃オクトーバーフェスト#天神祭#パレード・オブ・ナショナル・コスチュームズ',
            'correct_answer'=>'天神祭',
            'ganre_num'=>'3',
            'province_name'=>'2',
            'level_num'=>'3',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な城郭はどれか。',
            'pre_answer'=>'エディンバラ城＃ヴェルサイユ宮殿#松本城#ウィンザー城',
            'correct_answer'=>'松本城',
            'ganre_num'=>'3',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な温泉地はどれか。',
            'pre_answer'=>'バリ島＃ホノルル#伊豆半島#ラスベガス',
            'correct_answer'=>'伊豆半島',
            'ganre_num'=>'3',
            'province_name'=>'2',
            'level_num'=>'2',
        ]);
        Problem::create([
            'pstyle'=>'1',
            'answer_text'=>'次のうち、日本の代表的な庭園はどれか。',
            'pre_answer'=>'ベルサイユの庭園＃ケンブリッジ大学の庭園#金閣寺の庭園#バッキンガム宮殿の庭園',
            'correct_answer'=>'金閣寺の庭園',
            'ganre_num'=>'3',
            'province_name'=>'2',
            'level_num'=>'1',
        ]);
    }
}
